"""Plot Figure 13 from relative-hit-ratio CDF summary files.

Input:  data/RHR/withoutobjsize/<trace>_<cache-size>.dat
Output: relative_hit_ratio.pdf
"""
import os
import numpy as np
import matplotlib.pyplot as plt
from common import get_style

DATA_DIR = "data/RHR/withoutobjsize"

# Fixed 3x3 layout used by the paper figure.
TRACES = ["alibabaBlock", "tencentBlock", "cloudphysics"]
WSS = ["0.01", "0.03", "0.1"]
SKIP_ALGOS = {"CAR", "GLCACHE"}

# Load one CDF summary file. Rows are percentile points; columns are policies.
def load_dat(file_path):
    with open(file_path, "r") as f:
        lines = f.readlines()

    headers = lines[0].strip().split()
    data = {h: [] for h in headers}
    x_labels = []

    for line in lines[1:]:
        parts = line.strip().split()
        x_labels.append(parts[0])
        values = list(map(float, parts[1:]))

        for h, v in zip(headers, values):
            data[h].append(v)

    x = [int(p[1:]) for p in x_labels]
    return x, data, headers


# Main plotting routine.
def plot_all():
    fig, axes = plt.subplots(3, 3, figsize=(12, 10))
    axes = axes.reshape(3, 3)

    for i, wss in enumerate(WSS):
        for j, trace in enumerate(TRACES):
            ax = axes[i][j]

            # File names are generated by getRHRcdf.py.
            filename = f"{trace}_{wss}.dat"
            filepath = os.path.join(DATA_DIR, filename)

            if not os.path.exists(filepath):
                print(f"[WARNING] Missing file: {filepath}")
                continue

            x, data, headers = load_dat(filepath)
            real_x = x
            x_pos = np.arange(len(real_x))

            for alg in headers:
                alg_name = alg.upper()
                if alg_name in SKIP_ALGOS:
                    continue
                style = get_style(alg_name)
                z = 5 if alg_name == "MERLIN" else 3
                ax.plot(
                    x_pos,
                    data[alg],
                    zorder=z,
                    **style,
                )

            # Show trace names only in the first row.
            if i == 0:
                title_map = {
                    "alibabaBlock": "Alibaba",
                    "tencentBlock": "Tencent CBS",
                    "cloudphysics": "CloudPhysics"
                }
                ax.set_title(title_map.get(trace, trace), fontsize=12)

            # Show cache-size labels only in the first column.
            if j == 0:
                wss_label = {
                    "0.01": "Cache size: 1% WSS",
                    "0.03": "Cache size: 3% WSS",
                    "0.1": "Cache size: 10% WSS"
                }
                ax.set_ylabel(wss_label[wss])

            # Show the x-axis label only on the bottom row.
            if i == 2:
                ax.set_xlabel("Cumulative distribution (%)")

            ax.set_xticks(x_pos)
            ax.set_xticklabels(real_x)

            ax.grid(True, linestyle=":", alpha=0.6)

    # Shared legend below the grid.
    handles, labels = axes[0][0].get_legend_handles_labels()
    fig.legend(
        handles,
        labels,
        loc="lower center",
        ncol=5,
        fontsize=10,
        frameon=False
    )

    plt.tight_layout(rect=[0, 0.05, 1, 1])
    plt.savefig("relative_hit_ratio.pdf", dpi=300)
    plt.show()


if __name__ == "__main__":
    plot_all()
