#!/usr/bin/env python3
"""
example usage
python3 ./data_genmix.py -m 1000000 -n 200000000 --bin-output mix.oracleGeneral.bin
"""

import numpy as np
import struct

def gen_zipf(m: int, alpha: float, n: int, start: int = 0) -> np.ndarray:
    """generate zipf distributed workload

    Args:
        m (int): the number of objects
        alpha (float): the skewness
        n (int): the number of requests
        start (int, optional): start obj_id. Defaults to 0.

    Returns:
        requests that are zipf distributed 
    """

    np_tmp = np.power(np.arange(1, m + 1), -alpha)
    np_zeta = np.cumsum(np_tmp)
    dist_map = np_zeta / np_zeta[-1]
    r = np.random.uniform(0, 1, n)
    return np.searchsorted(dist_map, r) + start


def gen_uniform(m: int, n: int, start: int = 0) -> np.ndarray:
    """generate uniform distributed workload

    Args:
        m (int): the number of objects
        n (int): the number of requests
        start (int, optional): start obj_id. Defaults to 0.

    Returns:
        requests that are uniform distributed
    """

    return np.random.uniform(0, m, n).astype(int) + start

def gen_repeated_range(num_objects: int, repeats: int, start: int = 0) -> np.ndarray:
    """Generate a repeated scan-like sequence of contiguous object ids.

    Args:
        num_objects (int): number of unique objects
        repeats (int): number of full repeats
        start (int, optional): start obj_id. Defaults to 0.

    Returns:
        requests generated by repeating [start, start + num_objects)
    """
    object_ids = np.arange(start, start + num_objects)
    return np.tile(object_ids, repeats)


def build_steady_state_segment(small_churn: np.ndarray, first_half: np.ndarray,
                               mid_churn: np.ndarray, second_half: np.ndarray,
                               large_scan: np.ndarray) -> np.ndarray:
    """Compose the steady-state sequence from reusable building blocks."""
    return np.concatenate((small_churn, first_half, small_churn, mid_churn,
                           second_half, mid_churn, large_scan))


def build_workload_segments(
    p
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, int, int]:
    """Build warmup plus reusable pieces for steady-state generation."""
    zipf_requests = gen_zipf(p.m, p.alpha, int(p.m * p.zipf_ratio))
    small_churn_size = int(p.m * p.churn_ratio * 0.2)
    small_churn_base = p.m
    small_churn = gen_repeated_range(small_churn_size, 1, small_churn_base)

    mid_churn_size = int(p.m * p.churn_ratio * 0.8)
    mid_churn_base = small_churn_base + small_churn_size
    mid_churn = gen_repeated_range(mid_churn_size, 1, mid_churn_base)

    uniform_size = int(p.m * p.uniform_ratio)
    uniform_base = mid_churn_base + mid_churn_size
    uniform_requests = gen_repeated_range(uniform_size, p.uniform_multiplier,
                                           uniform_base)

    frequent_size = int(p.m * p.frequent_ratio)
    frequent_base = uniform_base + uniform_size
    frequent_requests = gen_repeated_range(frequent_size, p.frequent_repeats,
                                           frequent_base)

    # Shuffle these mixed segments to avoid fixed ordering bias.
    mixed_requests = np.concatenate((uniform_requests, zipf_requests,
                                     frequent_requests))
    np.random.shuffle(mixed_requests)

    scan_size = int(p.m * p.scan_ratio)
    scan_base = frequent_base + frequent_size

    first_half = mixed_requests[:len(mixed_requests) // 2]
    second_half = mixed_requests[len(mixed_requests) // 2:]

    #initial_large_scan = gen_repeated_range(large_scan_size, p.scan_repeats,
    #                                        large_scan_base)
    warmup_requests = np.concatenate((small_churn, mid_churn, small_churn,
                                      mixed_requests))#, initial_large_scan
    #warmup = np.concatenate((smallchurn, midscan, smallchurn, shuffled, bigscan))
    #shuffled_split1 = shuffled[0:len(shuffled)//2]
    #shuffled_split2 = shuffled[len(shuffled)//2:]
    #second = np.concatenate((smallchurn, shuffled_split1,smallchurn,midscan, shuffled_split2,midscan,bigscan))
    pattern_requests = np.concatenate((small_churn, first_half, small_churn, mid_churn, second_half, mid_churn))
    return (warmup_requests, pattern_requests, scan_size, scan_base)


def write_requests(requests: np.ndarray, start_index: int, output_file, record_struct,
                   obj_size: int, time_span: int, total_requests: int) -> int:
    """Write requests and return updated global request index."""
    request_index = start_index
    for obj_id in requests:
        request_index += 1
        timestamp = request_index * time_span // total_requests
        if output_file:
            output_file.write(record_struct.pack(timestamp, int(obj_id), obj_size, -2))
        else:
            print(int(obj_id))
    return request_index

#python3 ./data_genmix.py -m 1000000 -n 200000000 --bin-output mix.oracleGeneral.bin
if __name__ == "__main__":
    from argparse import ArgumentParser
    ap = ArgumentParser()
    ap.add_argument("-m", type=int, default=1000000, help="Number of objects")
    ap.add_argument("-n",
                    type=int,
                    default=200000000,
                    help="Number of requests")
    ap.add_argument("--alpha", type=float, default=1.0, help="Zipf parameter")
    ap.add_argument("--bin-output",
                    type=str,
                    default="",
                    help="Output to a file (oracleGeneral format)")
    ap.add_argument("--obj-size",
                    type=int,
                    default=4000,
                    help="Object size (used when output to a file)")
    ap.add_argument("--time-span",
                    type=int,
                    default=86400 * 7,
                    help="Time span of all requests in seconds")
    ap.add_argument("--zipf-ratio", type=float, default=0.6, help="Zipf distributed accessed in m")
    ap.add_argument("--churn-ratio", type=float, default=0.6, help="Total churn as a fraction of m")
    ap.add_argument("--uniform-ratio", type=float, default=0.6, help="Uniformly and random distributed accesses as a fraction of m")
    ap.add_argument("--uniform-multiplier", type=int, default=20, help="Number of uniform requests is this multiplier times the uniform-ratio * m")
    ap.add_argument("--frequent-ratio", type=float, default=0.2, help="Frequently accessed objects as a fraction of m")
    ap.add_argument("--frequent-repeats", type=int, default=30, help="Number of repeats for frequently accessed objects")
    ap.add_argument("--scan-ratio", type=float, default=0.6, help="Scan-like accesses as a fraction of m")
    ap.add_argument("--scan-repeats", type=int, default=1, help="Number of repeats for each large scan segment")

    p = ap.parse_args()

    output_file = open(p.bin_output, "wb") if p.bin_output else None
    request_record = struct.Struct("<IQIq")

    request_index = 0
    (warmup_requests, pattern_requests, scan_size, scan_base) = build_workload_segments(p)

    current_scan = gen_repeated_range(scan_size, 1, scan_base)

    request_index = write_requests(warmup_requests, request_index, output_file,
                                   request_record, p.obj_size, p.time_span, p.n)
    request_index = write_requests(current_scan, request_index, output_file, request_record,
                                   p.obj_size, p.time_span, p.n)

    while request_index < p.n:
        request_index = write_requests(pattern_requests, request_index,
                                       output_file, request_record, p.obj_size,
                                       p.time_span, p.n)
        request_index = write_requests(current_scan, request_index, output_file,
                                       request_record, p.obj_size, p.time_span,
                                       p.n)
        scan_base += scan_size
        current_scan = gen_repeated_range(scan_size,
                                       1,
                                       scan_base)

    if output_file:
        output_file.close()
