
#ifndef CACHELIB_ALLOCATOR_DATASTRUCT_MERLINCONFIG_H_
#define CACHELIB_ALLOCATOR_DATASTRUCT_MERLINCONFIG_H_
#define MAX_FREQ 7
#define THREAD_NUM 65
#define QUEUE_NUM 128
#define MAX_RETRIES 8
#endif // CACHELIB_ALLOCATOR_DATASTRUCT_MERLINCONFIG_H_